In [1]:
using Convex
using SCS
using Test

┌ Info: Recompiling stale cache file /Users/joerenes/.julia/compiled/v1.1/Convex/Sr0e5.ji for Convex [f65535da-76fb-5f13-bab9-19810c17039a]
└ @ Base loading.jl:1184


In [2]:
?partialtranspose

search: partialtranspose PartialTransposeAtom



```
partialtranspose(x, sys::Int, dims::Vector)
```

Returns the partial transpose of `x` over the `sys`th system, where `dims` is a vector of integers encoding the dimensions of each subsystem.


In [3]:
dims = [2,3,4]
d = prod(dims)
M = rand(ComplexF64,d,d)
R = ComplexVariable(d,d)


Variable of
size: (24, 24)
sign: ComplexSign()
vexity: AffineVexity()

In [4]:
pb = satisfy(partialtranspose(R, 3, dims) == M )
solve!(pb,SCSSolver(verbose=false))

In [5]:
TOL = 1e-3
@test partialtranspose(M,3,dims) ≈ evaluate(R) atol = TOL

Test Passed

In [5]:
TOL = 1e-3

0.001

In [4]:
dims = [2,3,4]
d = prod(dims)
A = rand(ComplexF64,2,2)
B = rand(ComplexF64,3,3)
C = rand(ComplexF64,4,4)
M = kron(A,B,C)
Mt1 = kron(transpose(A),B,C)
Mt2 = kron(A,transpose(B),C)
Mt3 = kron(A,B,transpose(C))

Rt1 = ComplexVariable(d,d)
Rt2 = ComplexVariable(d,d)
Rt3 = ComplexVariable(d,d)
S = rand(ComplexF64,d,d)
solve!(satisfy(partialtranspose(Rt1, 1, dims) == S ),SCSSolver(verbose=false))
solve!(satisfy(partialtranspose(Rt2, 2, dims) == S ),SCSSolver(verbose=false))
solve!(satisfy(partialtranspose(Rt3, 3, dims) == S ),SCSSolver(verbose=false))

@testset begin
@test partialtranspose(M,1,dims) ≈ Mt1 atol = TOL
@test partialtranspose(M,2,dims) ≈ Mt2 atol = TOL
@test partialtranspose(M,3,dims) ≈ Mt3 atol = TOL
@test partialtranspose(S,1,dims) ≈ evaluate(Rt1) atol = TOL
@test partialtranspose(S,2,dims) ≈ evaluate(Rt2) atol = TOL
@test partialtranspose(S,3,dims) ≈ evaluate(Rt3) atol = TOL
    
@test_throws ArgumentError partialtranspose(rand(6, 6), 3, [2, 3])
@test_throws ArgumentError partialtranspose(rand(6, 6), 1, [2, 4])
@test_throws ArgumentError partialtranspose(rand(3, 4), 1, [2, 3])
end

Test Summary: | Pass  Total
test set      |    9      9


Test.DefaultTestSet("test set", Any[], 9, false)

In [6]:
partialtranspose(rand(6,6), 3, [2, 3])

ArgumentError: ArgumentError: Invalid system, should between 1 and 2; got 3

In [9]:
size(x)

(6, 6)

In [6]:
partialtranspose(rand(6, 6), 3, [2, 3])

ErrorException: type Array has no field size

In [25]:
sum(abs.(reshape(partialtranspose(M,3,dims) - evaluate(R),:)))

1.6612020967877017e-12

In [22]:
pr = minimize(real(tr(R*rand(d,d))),[partialtranspose(R, 3, dims) == M])
solve!(pr,SCSSolver(verbose=false))

In [23]:
sum(abs.(reshape(partialtranspose(M,3,dims) - evaluate(R),:)))

0.001581196693364156

In [5]:
partialtranspose(tr,2,[dA,dB])

AbstractExpr with
head: partialtranspose
size: (6, 6)
sign: ComplexSign()
vexity: AffineVexity()


In [14]:
using LinearAlgebra
d=2
v=reshape(Matrix(I,d,d),:)
r = v* v'
Int.(partialtranspose(r,1,[d,d]))

4×4 Array{Int64,2}:
 1  0  0  0
 0  0  1  0
 0  1  0  0
 0  0  0  1

In [6]:
partialtranspose(A,1,[1,dA*dB*dC])

12×12 Array{Int64,2}:
  1  13  25  37  49  61  73  85   97  109  121  133
  2  14  26  38  50  62  74  86   98  110  122  134
  3  15  27  39  51  63  75  87   99  111  123  135
  4  16  28  40  52  64  76  88  100  112  124  136
  5  17  29  41  53  65  77  89  101  113  125  137
  6  18  30  42  54  66  78  90  102  114  126  138
  7  19  31  43  55  67  79  91  103  115  127  139
  8  20  32  44  56  68  80  92  104  116  128  140
  9  21  33  45  57  69  81  93  105  117  129  141
 10  22  34  46  58  70  82  94  106  118  130  142
 11  23  35  47  59  71  83  95  107  119  131  143
 12  24  36  48  60  72  84  96  108  120  132  144

In [17]:
partialtranspose(A,2,[dA*dB*dC,1])

12×12 Array{Int64,2}:
  1  13  25  37  49  61  73  85   97  109  121  133
  2  14  26  38  50  62  74  86   98  110  122  134
  3  15  27  39  51  63  75  87   99  111  123  135
  4  16  28  40  52  64  76  88  100  112  124  136
  5  17  29  41  53  65  77  89  101  113  125  137
  6  18  30  42  54  66  78  90  102  114  126  138
  7  19  31  43  55  67  79  91  103  115  127  139
  8  20  32  44  56  68  80  92  104  116  128  140
  9  21  33  45  57  69  81  93  105  117  129  141
 10  22  34  46  58  70  82  94  106  118  130  142
 11  23  35  47  59  71  83  95  107  119  131  143
 12  24  36  48  60  72  84  96  108  120  132  144

In [10]:
?partialtranspose

search: partialtranspose PartialTransposeAtom



No documentation found.

`Convex.partialtranspose` is a `Function`.

```
# 2 methods for generic function "partialtranspose":
[1] partialtranspose(x::AbstractArray{T,2} where T, sys::Int64, dims::Array{T,1} where T) in Convex at /Users/joerenes/.julia/dev/Convex/src/atoms/affine/partialtranspose.jl:46
[2] partialtranspose(x::AbstractExpr, sys::Int64, dim::Array{T,1} where T) in Convex at /Users/joerenes/.julia/dev/Convex/src/atoms/affine/partialtranspose.jl:89
```


In [8]:
conic_form!(rer)

ConicObj(OrderedCollections.OrderedDict{UInt64,Tuple{Union{Number, AbstractArray},Union{Number, AbstractArray}}}(0x4bff9badaa77fdf2=>(
  [1 ,  1]  =  1.0
  [2 ,  2]  =  1.0
  [3 ,  3]  =  1.0
  [19,  4]  =  1.0
  [20,  5]  =  1.0
  [21,  6]  =  1.0
  [7 ,  7]  =  1.0
  [8 ,  8]  =  1.0
  [9 ,  9]  =  1.0
  [25, 10]  =  1.0
  [26, 11]  =  1.0
  [27, 12]  =  1.0
  ⋮
  [10, 25]  =  1.0
  [11, 26]  =  1.0
  [12, 27]  =  1.0
  [28, 28]  =  1.0
  [29, 29]  =  1.0
  [30, 30]  =  1.0
  [16, 31]  =  1.0
  [17, 32]  =  1.0
  [18, 33]  =  1.0
  [34, 34]  =  1.0
  [35, 35]  =  1.0
  [36, 36]  =  1.0, 
  [1 ,  1]  =  0.0+1.0im
  [2 ,  2]  =  0.0+1.0im
  [3 ,  3]  =  0.0+1.0im
  [19,  4]  =  0.0+1.0im
  [20,  5]  =  0.0+1.0im
  [21,  6]  =  0.0+1.0im
  [7 ,  7]  =  0.0+1.0im
  [8 ,  8]  =  0.0+1.0im
  [9 ,  9]  =  0.0+1.0im
  [25, 10]  =  0.0+1.0im
  [26, 11]  =  0.0+1.0im
  [27, 12]  =  0.0+1.0im
  ⋮
  [10, 25]  =  0.0+1.0im
  [11, 26]  =  0.0+1.0im
  [12, 27]  =  0.0+1.0im
  [28, 28]  =  0.0+1.0im